version: 0.0
os: linux

files:
  - source: /
    destination: /src/kafka-producer   # 한글: 아카이브 루트 → 배포경로

file_exists_behavior: OVERWRITE        # 한글: 기존파일 덮어쓰기

permissions:
  - object: /src/kafka-producer
    pattern: "**"                      # 한글: 하위 전체
    owner: kafka
    group: kafka
    mode: 755

hooks:
  ApplicationStop:                     # 한글: 기존 서비스 중지(존재시)
    - location: deploy/application_stop.sh
      timeout: 120
      runas: root

  BeforeInstall:                       # 한글: 경로/계정 준비
    - location: deploy/before_install.sh
      timeout: 120
      runas: root

  AfterInstall:                        # 한글: 서비스 유닛 설치/권한/환경
    - location: deploy/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:                    # 한글: 서비스 시작
    - location: deploy/application_start.sh
      timeout: 180
      runas: root

  ValidateService:                     # 한글: 기동 확인
    - location: deploy/validate_service.sh
      timeout: 120
      runas: root
